// Blog posts — most-searched implant & dentistry topics, answer-first for AI/search.
export const POSTS = [
  { slug: "dental-implant-cost-glendale", image: "/images/ph-consult.jpg", title: "How Much Do Dental Implants Cost in Glendale, CA?",
    description: "Single implants in Glendale commonly run $4,000–$6,000+ once every stage is billed. Why the range is so wide, what a complete quote must include, and how a fixed $2,000 option 15 minutes away compares.",
    date: "2026-08-07", read: "5 min", tag: "Glendale",
    excerpt: "Glendale implant quotes routinely pass $5,000. Here's what drives that — and what to check before you sign." },
  { slug: "dental-implant-cost-burbank", image: "/images/ph-consult-tight.jpg", title: "How Much Do Dental Implants Cost in Burbank, CA?",
    description: "What Burbank patients actually pay for a dental implant, why quotes vary by thousands, and the questions that separate a complete price from a partial one.",
    date: "2026-08-07", read: "5 min", tag: "Burbank",
    excerpt: "Two Burbank offices can quote the same implant $3,000 apart. The difference usually isn't quality." },
  { slug: "dental-implant-cost-pasadena", image: "/images/ph-implantmodel.jpg", title: "How Much Do Dental Implants Cost in Pasadena, CA?",
    description: "Pasadena implant pricing explained: what the fee actually covers, why specialist referral chains raise the total, and how to compare quotes accurately.",
    date: "2026-08-07", read: "5 min", tag: "Pasadena",
    excerpt: "Pasadena has excellent implant dentistry — and some of the highest quotes in the county. Here's how to read them." },

  { slug: "gum-disease-and-implants", image: "/images/ph-op-1.jpg", title: "Gum Disease and Dental Implants: The Link That Decides Success",
    description: "Gum disease is the leading cause of late implant failure. Why periodontal health must be treated before implants are placed — and why having one doctor do both matters.",
    date: "2026-08-06", read: "5 min", tag: "Gum Health",
    excerpt: "Titanium never gets infected. The tissue around it does — and that's what determines whether an implant lasts a lifetime." },
  { slug: "sedation-for-dental-implants", image: "/images/ph-op-3.jpg", title: "Sedation for Dental Implants: Who Actually Needs It?",
    description: "Sedation isn't necessary for most implant procedures — but for patients whose fear has delayed treatment for years, it changes everything. An honest guide to who benefits.",
    date: "2026-08-06", read: "4 min", tag: "Comfort & Sedation",
    excerpt: "There's no prize for being brave, and no shame in asking. How to tell if sedation is right for your implant surgery." },

  { slug: "dental-implants-for-seniors", image: "/images/ph-op-3.jpg", title: "Dental Implants for Seniors: Is 70 or 80 Too Old?",
    description: "Age itself almost never disqualifies someone from dental implants — health and bone do. What older patients should know about candidacy, healing, medications, and cost.",
    date: "2026-08-05", read: "5 min", tag: "Seniors",
    excerpt: "The most common reason people over 70 skip implants is a belief that turns out to be false." },
  { slug: "all-on-4-explained", image: "/images/ph-implantmodel.jpg", title: "All-on-4 Explained: A Full Arch of Teeth on Four Implants",
    description: "How full-arch implant treatment works, who it suits, what it costs, and the honest trade-offs versus dentures and individual implants.",
    date: "2026-08-05", read: "6 min", tag: "Full-Arch Implants",
    excerpt: "Replacing every tooth one implant at a time isn't necessary — or affordable. Here's what full-arch actually involves." },
  { slug: "not-enough-bone-for-implants", image: "/images/ph-consult.jpg", title: "\"You Don't Have Enough Bone for Implants\" — Is That Still True?",
    description: "Bone loss is the most common reason patients are told no to implants. Bone grafting, sinus lifts, and modern planning have changed that answer for many people.",
    date: "2026-08-05", read: "5 min", tag: "Dental Implants",
    excerpt: "Told no somewhere else, years ago? That verdict may have expired." },
  { slug: "bleeding-gums-what-it-means", image: "/images/ph-op-2.jpg", title: "Bleeding Gums: What Your Mouth Is Warning You About",
    description: "Gums that bleed when you brush are not normal. What gum disease actually is, how it connects to heart health and diabetes, and how it's reversed in the early stage.",
    date: "2026-08-05", read: "5 min", tag: "Gum Health",
    excerpt: "The most ignored symptom in dentistry — and the one most connected to the rest of your body." },
  { slug: "childs-first-dental-visit", image: "/images/ph-reception.jpg", title: "Your Child's First Dental Visit: A Parent's Guide",
    description: "When to schedule the first visit, what actually happens, how to prepare a nervous child, and the words parents should avoid using beforehand.",
    date: "2026-08-05", read: "4 min", tag: "Kids & Families",
    excerpt: "How you talk about the dentist at home matters more than anything that happens in the chair." },
  { slug: "invisalign-vs-braces-adults", image: "/images/ph-aligner-tight.jpg", title: "Invisalign vs. Braces for Adults: How to Choose",
    description: "A practical comparison for adults considering orthodontics — appearance, treatment time, cost, discipline required, and which cases still need traditional braces.",
    date: "2026-08-05", read: "5 min", tag: "Invisalign",
    excerpt: "Aligners win on appearance. They lose on one thing that surprises most adults." },
  { slug: "dental-care-without-insurance", image: "/images/ph-consult-tight.jpg", title: "How to Get Dental Work Done Without Insurance",
    description: "A practical guide for uninsured patients: what things actually cost, which treatments to prioritize, how to spot incomplete quotes, and questions that protect you from surprise bills.",
    date: "2026-08-05", read: "5 min", tag: "Cost & Insurance",
    excerpt: "Most dental insurance caps out around $1,500 a year anyway. Here's how uninsured patients get care without ambush bills." },

  { slug: "how-much-do-dental-implants-cost", image: "/images/ph-consult-tight.jpg", title: "How Much Do Dental Implants Cost in 2026? (Real Numbers)",
    description: "US single implants average $3,000–$5,000+. Here's what drives the price, what 'hidden fees' look like, and how Sunland Dental Care offers a complete implant for $2,000 fixed.",
    date: "2026-08-04", read: "5 min", tag: "Dental Implants",
    excerpt: "Cost is the #1 question patients Google about implants — and the most misunderstood. Here are the real numbers, including ours." },
  { slug: "do-dental-implants-hurt", image: "/images/ph-op-2.jpg", title: "Do Dental Implants Hurt? What Patients Actually Feel",
    description: "Implant placement is done under local anesthesia — most patients feel pressure, not pain, and recovery is milder than a tooth extraction. What to actually expect, day by day.",
    date: "2026-08-04", read: "4 min", tag: "Dental Implants",
    excerpt: "The fear is worse than the procedure. What implant surgery actually feels like — during, that night, and the week after." },
  { slug: "how-long-do-dental-implants-last", image: "/images/ph-implantmodel.jpg", title: "How Long Do Dental Implants Last? (And What Makes Them Fail)",
    description: "Well-placed dental implants routinely last decades — often a lifetime. The implant itself rarely fails; the gums around it do. Here's what determines whether yours lasts.",
    date: "2026-08-04", read: "4 min", tag: "Dental Implants",
    excerpt: "Implants can outlast the rest of your teeth — if one thing is protected. It isn't the titanium." },
  { slug: "implants-vs-dentures-vs-bridges", image: "/images/ph-consult.jpg", title: "Implants vs. Dentures vs. Bridges: An Honest Comparison",
    description: "A dentist's honest comparison of the three ways to replace missing teeth — cost, comfort, longevity, and bone health — and who each option genuinely suits.",
    date: "2026-08-04", read: "6 min", tag: "Tooth Replacement",
    excerpt: "Each option is right for somebody. A 40-year implantologist on who should pick which — including when NOT to choose implants." },
  { slug: "why-does-my-tooth-hurt", image: "/images/ph-op-1.jpg", title: "Why Does My Tooth Hurt? 7 Causes, From Harmless to Urgent",
    description: "Tooth pain decoded: sensitivity, pain when biting, throbbing at night, swelling. Which causes can wait for an appointment and which mean call the dentist today.",
    date: "2026-08-04", read: "5 min", tag: "Toothache",
    excerpt: "Your tooth is telling you something specific. How to read the type of pain — and know when it's an emergency." },
  { slug: "afraid-of-the-dentist", image: "/images/ph-reception.jpg", title: "Haven't Seen a Dentist in Years? Read This First",
    description: "Dental anxiety and embarrassment keep millions away from care. What actually happens when you finally come back — and why a judgment-free first visit changes everything.",
    date: "2026-08-04", read: "4 min", tag: "Dental Anxiety",
    excerpt: "No lectures, no shame. What the first visit back really looks like after 5, 10, or 20 years away." },
];
