// Blog posts — most-searched implant & dentistry topics, answer-first for AI/search.
export const POSTS = [
  { slug: "teeth-sensitive-to-cold", image: "/images/hero-exam.jpg", title: "Why Are My Teeth Suddenly Sensitive to Cold?",
    description: "Sudden cold sensitivity usually means exposed dentin, a cracked tooth, gum recession, or a failing filling. How to tell which one you have — and which types mean call a dentist this week.",
    date: "2026-08-14", read: "5 min", tag: "Symptoms",
    excerpt: "How long the zing lasts tells you almost everything. Under ten seconds is one problem; lingering is another." },
  { slug: "bad-breath-wont-go-away", image: "/images/office-waiting.webp", title: "Why Does My Breath Smell Even After Brushing?",
    description: "Persistent bad breath usually isn't a hygiene failure — it's bacteria living where a toothbrush can't reach: below the gumline, on the tongue, or around a failing filling. The real causes and fixes.",
    date: "2026-08-14", read: "5 min", tag: "Symptoms",
    excerpt: "If mouthwash only buys you an hour, the problem isn't your brushing. It's where the bacteria are living." },
  { slug: "wake-up-with-jaw-pain", image: "/images/hero-hallway.webp", title: "Why Do I Wake Up With Jaw Pain and Headaches?",
    description: "Morning jaw pain, temple headaches, and worn or sensitive teeth usually point to nighttime grinding (bruxism). What it does to your teeth over time and what actually stops the damage.",
    date: "2026-08-14", read: "5 min", tag: "Symptoms",
    excerpt: "Your dentist can often tell you're grinding before you know it — the evidence is worn into the teeth." },
  { slug: "loose-tooth-in-adults", image: "/images/dr-emami-hero.webp", title: "My Tooth Feels Loose — Is That an Emergency?",
    description: "A loose adult tooth is never normal. Whether it's from gum disease, trauma, grinding, or infection, here's how urgent it is and what determines whether the tooth can be saved.",
    date: "2026-08-14", read: "5 min", tag: "Symptoms",
    excerpt: "Adults don't get loose teeth. If one moves, something is holding it that shouldn't be letting go." },
  { slug: "why-are-my-gums-receding", image: "/images/dr-emami-magnolia.webp", title: "Why Are My Gums Receding? (And Can They Grow Back?)",
    description: "Receding gums expose the root, cause sensitivity, and don't grow back on their own. What causes recession — including brushing too hard — and what treatments genuinely help.",
    date: "2026-08-14", read: "5 min", tag: "Gum Health",
    excerpt: "The honest answer to 'can gums grow back' is no. But that's not the end of the conversation." },
  { slug: "tooth-extraction-healing-time", image: "/images/office-waiting.jpg", title: "How Long Does It Take to Heal After a Tooth Extraction?",
    description: "A day-by-day recovery timeline after a tooth extraction, what dry socket feels like and how to avoid it, when to call, and why what you do in the first 24 hours matters most.",
    date: "2026-08-14", read: "6 min", tag: "Aftercare",
    excerpt: "The first 24 hours decide whether the next week is easy or miserable. Here's exactly what to do." },
  { slug: "what-dental-insurance-actually-covers", image: "/images/hero-consultdesk.webp", title: "What Dental Insurance Actually Covers (And What It Doesn't)",
    description: "Most dental plans follow a 100/80/50 structure with an annual maximum around $1,000-$2,000. What that means in practice, why implants are often excluded, and how to check your real coverage before treatment.",
    date: "2026-08-14", read: "6 min", tag: "Cost & Insurance",
    excerpt: "Your plan's annual maximum hasn't meaningfully risen since the 1970s. That one fact explains most of the confusion." },
  { slug: "tooth-pain-at-night-dentist-closed", image: "/images/hero-treatment.webp", title: "Tooth Pain at Night and the Dentist Is Closed: What to Do Now",
    description: "Practical steps for managing dental pain after hours — what helps, what makes it worse, which symptoms mean the emergency room instead of waiting, and how to be first in line in the morning.",
    date: "2026-08-14", read: "5 min", tag: "Emergency",
    excerpt: "Pain always peaks at 2 a.m. Here's what actually helps until morning — and the symptoms that can't wait." },

  { slug: "cheap-dental-implant-ads-truth", image: "/images/ph-implants-sign.jpg", title: "The Truth About \"Cheap\" Dental Implant Ads: What a $499 Implant Actually Costs",
    description: "Why advertised dental implant prices of $499, $799, or $999 are almost never what you pay. A component-by-component breakdown of what a complete implant genuinely costs to provide — and how to spot a partial quote before you sign.",
    date: "2026-08-11", read: "8 min", tag: "Dental Implants",
    excerpt: "Do the math on what an implant costs to actually provide, and the advertised numbers stop making sense. Here's the arithmetic nobody shows you." },
  { slug: "dental-tourism-implants-mexico-turkey", image: "/images/hero-consult.jpg", title: "Getting Dental Implants Abroad: The Real Math on Mexico and Turkey",
    description: "Dental tourism for implants can genuinely save money — but the honest calculation includes travel, follow-up, healing timelines, and what happens when something needs adjusting. An implant dentist's balanced take.",
    date: "2026-08-11", read: "7 min", tag: "Dental Implants",
    excerpt: "Sometimes it's a great decision. Sometimes the savings evaporate on the second flight. Here's how to tell which one you're looking at." },
  { slug: "dental-implant-brands-does-it-matter", image: "/images/hero-chair.jpg", title: "Does the Brand of Dental Implant Matter? What to Ask Your Dentist",
    description: "Not all dental implants are the same. Why the implant system your dentist uses affects long-term repairability, what questions to ask, and why the brand matters most a decade after placement.",
    date: "2026-08-11", read: "5 min", tag: "Dental Implants",
    excerpt: "The brand barely matters on surgery day. It matters enormously in year twelve, when a part needs replacing." },
  { slug: "same-day-dental-implants-explained", image: "/images/dr-emami-office.jpg", title: "\"Same-Day\" Dental Implants: What's Real and What's Marketing",
    description: "Immediate-load implants are real dentistry, but the phrase \"teeth in a day\" hides an important distinction between temporary and final teeth. What actually happens on day one, and who qualifies.",
    date: "2026-08-11", read: "5 min", tag: "Dental Implants",
    excerpt: "You can leave with teeth the same day. They're just not the teeth you'll keep — and that's fine, if someone tells you." },
  { slug: "what-happens-missing-tooth-not-replaced", image: "/images/aligner-closeup.jpg", title: "What Happens If You Don't Replace a Missing Tooth?",
    description: "A missing tooth doesn't stay a single problem. Bone loss, shifting teeth, bite collapse, and the way waiting turns a straightforward implant into a more complex one.",
    date: "2026-08-11", read: "5 min", tag: "Tooth Replacement",
    excerpt: "The gap is the least of it. What happens over the following five years is the part nobody warns you about." },

  { slug: "emergency-dentist-tujunga", image: "/images/ph-op-light.jpg", title: "Emergency Dentist Near Tujunga: What to Do Right Now",
    description: "Dental emergency in Tujunga? What to do in the first 30 minutes for a knocked-out tooth, broken tooth, swelling, or severe pain — and when to call an office five minutes away versus going to the ER.",
    date: "2026-08-08", read: "5 min", tag: "Tujunga",
    excerpt: "The first thirty minutes matter most. What to do right now, and which problems can't wait until Monday." },
  { slug: "dentista-que-habla-espanol-sun-valley", image: "/images/ph-clinic-floor.jpg", title: "Dentista Que Habla Español Cerca de Sun Valley",
    description: "Buscando un dentista que hable español cerca de Sun Valley, CA? Sunland Dental Care atiende en español a diez minutos, con precios fijos publicados e implantes completos por $2,000.",
    date: "2026-08-08", read: "5 min", tag: "Sun Valley · Español",
    excerpt: "Entender su tratamiento no debería depender del inglés. Atención en español a diez minutos de Sun Valley." },
  { slug: "second-opinion-dentist-la-canada", image: "/images/ph-credentials.jpg", title: "Getting a Second Opinion on a Dental Treatment Plan (La Cañada & Foothills)",
    description: "Quoted thousands for dental work you're unsure about? How to get a genuine second opinion near La Cañada Flintridge, what to bring, and the questions that separate necessary treatment from optional.",
    date: "2026-08-08", read: "6 min", tag: "La Cañada",
    excerpt: "A second opinion isn't disloyalty — it's how you find out whether a $12,000 plan was really necessary." },
  { slug: "all-on-4-cost-glendale", image: "/images/ph-model-hands.jpg", title: "All-on-4 Cost Near Glendale: What Full-Arch Implants Really Run",
    description: "Full-arch All-on-4 implants near Glendale typically run $20,000–$30,000+ per arch. What drives the price, what a complete quote must include, and how to compare offers accurately.",
    date: "2026-08-08", read: "6 min", tag: "Glendale",
    excerpt: "Full-arch quotes vary by tens of thousands. Almost none of that variance is the implants themselves." },
  { slug: "cosmetic-dentist-burbank-veneers", image: "/images/ph-consult-face.jpg", title: "Veneers Near Burbank: What They Cost and How to Avoid the Overdone Look",
    description: "Considering veneers near Burbank? What porcelain veneers cost, how conservative preparation protects your teeth, and how to get results that read as a naturally good smile rather than obvious dental work.",
    date: "2026-08-08", read: "5 min", tag: "Burbank",
    excerpt: "Everyone can spot bad veneers. The good ones you've simply never noticed." },
  { slug: "dentures-seniors-la-crescenta", image: "/images/ph-coat-lower.jpg", title: "Dentures vs. Implant Dentures for Seniors Near La Crescenta",
    description: "A practical comparison for older adults near La Crescenta-Montrose: conventional dentures, implant-supported dentures, and what each actually costs in comfort, chewing power, and bone health over time.",
    date: "2026-08-08", read: "6 min", tag: "La Crescenta",
    excerpt: "The lower denture that never stays put has a fix — and it costs less than most people assume." },
  { slug: "dentist-for-anxious-patients-foothills", image: "/images/ph-clinic-chair.jpg", title: "Finding a Dentist for Anxious Patients in the Foothill Communities",
    description: "Dental fear affects most adults. How to find a dentist who accommodates anxiety near Sunland, Tujunga, La Crescenta, and Glendale — the questions to ask when booking, and what a calm first visit looks like.",
    date: "2026-08-08", read: "5 min", tag: "Dental Anxiety",
    excerpt: "The right question to ask when booking isn't about sedation. It's much simpler than that." },
  { slug: "affordable-dentist-no-insurance-san-fernando-valley", image: "/images/ph-giftcard.jpg", title: "Affordable Dentist Without Insurance in the San Fernando Valley",
    description: "Uninsured dental care in the San Fernando Valley: what treatments actually cost, how to triage by urgency, how to spot an incomplete quote, and which practices publish fixed prices.",
    date: "2026-08-08", read: "5 min", tag: "Cost & Insurance",
    excerpt: "Uninsured doesn't mean untreated. How to get real care without an ambush bill." },

  { slug: "dental-implant-cost-glendale", image: "/images/ph-consult.jpg", title: "How Much Do Dental Implants Cost in Glendale, CA?",
    description: "Single implants in Glendale commonly run $4,000–$6,000+ once every stage is billed. Why the range is so wide, what a complete quote must include, and how a fixed $2,000 option 15 minutes away compares.",
    date: "2026-08-07", read: "5 min", tag: "Glendale",
    excerpt: "Glendale implant quotes routinely pass $5,000. Here's what drives that — and what to check before you sign." },
  { slug: "dental-implant-cost-burbank", image: "/images/ph-implants-sign.jpg", title: "How Much Do Dental Implants Cost in Burbank, CA?",
    description: "What Burbank patients actually pay for a dental implant, why quotes vary by thousands, and the questions that separate a complete price from a partial one.",
    date: "2026-08-07", read: "5 min", tag: "Burbank",
    excerpt: "Two Burbank offices can quote the same implant $3,000 apart. The difference usually isn't quality." },
  { slug: "dental-implant-cost-pasadena", image: "/images/ph-implantmodel.jpg", title: "How Much Do Dental Implants Cost in Pasadena, CA?",
    description: "Pasadena implant pricing explained: what the fee actually covers, why specialist referral chains raise the total, and how to compare quotes accurately.",
    date: "2026-08-07", read: "5 min", tag: "Pasadena",
    excerpt: "Pasadena has excellent implant dentistry — and some of the highest quotes in the county. Here's how to read them." },

  { slug: "gum-disease-and-implants", image: "/images/ph-op-1.jpg", title: "Gum Disease and Dental Implants: The Link That Decides Success",
    description: "Gum disease is the leading cause of late implant failure. Why periodontal health must be treated before implants are placed — and why having one doctor do both matters.",
    date: "2026-08-06", read: "5 min", tag: "Gum Health",
    excerpt: "Titanium never gets infected. The tissue around it does — and that's what determines whether an implant lasts a lifetime." },
  { slug: "sedation-for-dental-implants", image: "/images/ph-op-3.jpg", title: "Sedation for Dental Implants: Who Actually Needs It?",
    description: "Sedation isn't necessary for most implant procedures — but for patients whose fear has delayed treatment for years, it changes everything. An honest guide to who benefits.",
    date: "2026-08-06", read: "4 min", tag: "Comfort & Sedation",
    excerpt: "There's no prize for being brave, and no shame in asking. How to tell if sedation is right for your implant surgery." },

  { slug: "dental-implants-for-seniors", image: "/images/ph-coat-reception.jpg", title: "Dental Implants for Seniors: Is 70 or 80 Too Old?",
    description: "Age itself almost never disqualifies someone from dental implants — health and bone do. What older patients should know about candidacy, healing, medications, and cost.",
    date: "2026-08-05", read: "5 min", tag: "Seniors",
    excerpt: "The most common reason people over 70 skip implants is a belief that turns out to be false." },
  { slug: "all-on-4-explained", image: "/images/ph-patient-side.jpg", title: "All-on-4 Explained: A Full Arch of Teeth on Four Implants",
    description: "How full-arch implant treatment works, who it suits, what it costs, and the honest trade-offs versus dentures and individual implants.",
    date: "2026-08-05", read: "6 min", tag: "Full-Arch Implants",
    excerpt: "Replacing every tooth one implant at a time isn't necessary — or affordable. Here's what full-arch actually involves." },
  { slug: "not-enough-bone-for-implants", image: "/images/ph-consult-tight.jpg", title: "\"You Don't Have Enough Bone for Implants\" — Is That Still True?",
    description: "Bone loss is the most common reason patients are told no to implants. Bone grafting, sinus lifts, and modern planning have changed that answer for many people.",
    date: "2026-08-05", read: "5 min", tag: "Dental Implants",
    excerpt: "Told no somewhere else, years ago? That verdict may have expired." },
  { slug: "bleeding-gums-what-it-means", image: "/images/ph-op-2.jpg", title: "Bleeding Gums: What Your Mouth Is Warning You About",
    description: "Gums that bleed when you brush are not normal. What gum disease actually is, how it connects to heart health and diabetes, and how it's reversed in the early stage.",
    date: "2026-08-05", read: "5 min", tag: "Gum Health",
    excerpt: "The most ignored symptom in dentistry — and the one most connected to the rest of your body." },
  { slug: "childs-first-dental-visit", image: "/images/ph-orchids.jpg", title: "Your Child's First Dental Visit: A Parent's Guide",
    description: "When to schedule the first visit, what actually happens, how to prepare a nervous child, and the words parents should avoid using beforehand.",
    date: "2026-08-05", read: "4 min", tag: "Kids & Families",
    excerpt: "How you talk about the dentist at home matters more than anything that happens in the chair." },
  { slug: "invisalign-vs-braces-adults", image: "/images/ph-aligner-hands.jpg", title: "Invisalign vs. Braces for Adults: How to Choose",
    description: "A practical comparison for adults considering orthodontics — appearance, treatment time, cost, discipline required, and which cases still need traditional braces.",
    date: "2026-08-05", read: "5 min", tag: "Invisalign",
    excerpt: "Aligners win on appearance. They lose on one thing that surprises most adults." },
  { slug: "dental-care-without-insurance", image: "/images/ph-portrait-tight.jpg", title: "How to Get Dental Work Done Without Insurance",
    description: "A practical guide for uninsured patients: what things actually cost, which treatments to prioritize, how to spot incomplete quotes, and questions that protect you from surprise bills.",
    date: "2026-08-05", read: "5 min", tag: "Cost & Insurance",
    excerpt: "Most dental insurance caps out around $1,500 a year anyway. Here's how uninsured patients get care without ambush bills." },

  { slug: "how-much-do-dental-implants-cost", image: "/images/ph-clinic-wide.jpg", title: "How Much Do Dental Implants Cost in 2026? (Real Numbers)",
    description: "US single implants average $3,000–$5,000+. Here's what drives the price, what 'hidden fees' look like, and how Sunland Dental Care offers a complete implant for $2,000 fixed.",
    date: "2026-08-04", read: "5 min", tag: "Dental Implants",
    excerpt: "Cost is the #1 question patients Google about implants — and the most misunderstood. Here are the real numbers, including ours." },
  { slug: "do-dental-implants-hurt", image: "/images/office-operatory.webp", title: "Do Dental Implants Hurt? What Patients Actually Feel",
    description: "Implant placement is done under local anesthesia — most patients feel pressure, not pain, and recovery is milder than a tooth extraction. What to actually expect, day by day.",
    date: "2026-08-04", read: "4 min", tag: "Dental Implants",
    excerpt: "The fear is worse than the procedure. What implant surgery actually feels like — during, that night, and the week after." },
  { slug: "how-long-do-dental-implants-last", image: "/images/ph-coat-white.jpg", title: "How Long Do Dental Implants Last? (And What Makes Them Fail)",
    description: "Well-placed dental implants routinely last decades — often a lifetime. The implant itself rarely fails; the gums around it do. Here's what determines whether yours lasts.",
    date: "2026-08-04", read: "4 min", tag: "Dental Implants",
    excerpt: "Implants can outlast the rest of your teeth — if one thing is protected. It isn't the titanium." },
  { slug: "implants-vs-dentures-vs-bridges", image: "/images/ph-aligner-tight.jpg", title: "Implants vs. Dentures vs. Bridges: An Honest Comparison",
    description: "A dentist's honest comparison of the three ways to replace missing teeth — cost, comfort, longevity, and bone health — and who each option genuinely suits.",
    date: "2026-08-04", read: "6 min", tag: "Tooth Replacement",
    excerpt: "Each option is right for somebody. A 40-year implantologist on who should pick which — including when NOT to choose implants." },
  { slug: "why-does-my-tooth-hurt", image: "/images/hero-treatment.jpg", title: "Why Does My Tooth Hurt? 7 Causes, From Harmless to Urgent",
    description: "Tooth pain decoded: sensitivity, pain when biting, throbbing at night, swelling. Which causes can wait for an appointment and which mean call the dentist today.",
    date: "2026-08-04", read: "5 min", tag: "Toothache",
    excerpt: "Your tooth is telling you something specific. How to read the type of pain — and know when it's an emergency." },
  { slug: "afraid-of-the-dentist", image: "/images/ph-reception.jpg", title: "Haven't Seen a Dentist in Years? Read This First",
    description: "Dental anxiety and embarrassment keep millions away from care. What actually happens when you finally come back — and why a judgment-free first visit changes everything.",
    date: "2026-08-04", read: "4 min", tag: "Dental Anxiety",
    excerpt: "No lectures, no shame. What the first visit back really looks like after 5, 10, or 20 years away." },
];
