// Blog posts — most-searched implant & dentistry topics, answer-first for AI/search.
export const POSTS = [
  { slug: "how-much-do-dental-implants-cost", title: "How Much Do Dental Implants Cost in 2026? (Real Numbers)",
    description: "US single implants average $3,000–$5,000+. Here's what drives the price, what 'hidden fees' look like, and how Sunland Dental Care offers a complete implant for $2,000 fixed.",
    date: "2026-08-04", read: "5 min", tag: "Dental Implants",
    excerpt: "Cost is the #1 question patients Google about implants — and the most misunderstood. Here are the real numbers, including ours." },
  { slug: "do-dental-implants-hurt", title: "Do Dental Implants Hurt? What Patients Actually Feel",
    description: "Implant placement is done under local anesthesia — most patients feel pressure, not pain, and recovery is milder than a tooth extraction. What to actually expect, day by day.",
    date: "2026-08-04", read: "4 min", tag: "Dental Implants",
    excerpt: "The fear is worse than the procedure. What implant surgery actually feels like — during, that night, and the week after." },
  { slug: "how-long-do-dental-implants-last", title: "How Long Do Dental Implants Last? (And What Makes Them Fail)",
    description: "Well-placed dental implants routinely last decades — often a lifetime. The implant itself rarely fails; the gums around it do. Here's what determines whether yours lasts.",
    date: "2026-08-04", read: "4 min", tag: "Dental Implants",
    excerpt: "Implants can outlast the rest of your teeth — if one thing is protected. It isn't the titanium." },
  { slug: "implants-vs-dentures-vs-bridges", title: "Implants vs. Dentures vs. Bridges: An Honest Comparison",
    description: "A dentist's honest comparison of the three ways to replace missing teeth — cost, comfort, longevity, and bone health — and who each option genuinely suits.",
    date: "2026-08-04", read: "6 min", tag: "Tooth Replacement",
    excerpt: "Each option is right for somebody. A 40-year implantologist on who should pick which — including when NOT to choose implants." },
  { slug: "why-does-my-tooth-hurt", title: "Why Does My Tooth Hurt? 7 Causes, From Harmless to Urgent",
    description: "Tooth pain decoded: sensitivity, pain when biting, throbbing at night, swelling. Which causes can wait for an appointment and which mean call the dentist today.",
    date: "2026-08-04", read: "5 min", tag: "Toothache",
    excerpt: "Your tooth is telling you something specific. How to read the type of pain — and know when it's an emergency." },
  { slug: "afraid-of-the-dentist", title: "Haven't Seen a Dentist in Years? Read This First",
    description: "Dental anxiety and embarrassment keep millions away from care. What actually happens when you finally come back — and why a judgment-free first visit changes everything.",
    date: "2026-08-04", read: "4 min", tag: "Dental Anxiety",
    excerpt: "No lectures, no shame. What the first visit back really looks like after 5, 10, or 20 years away." },
];
